/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5Y7IPzZBRTM
 */
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export function Dating2() {
  return (
    <div className="bg-[#fffbe6]">
      <nav className="bg-white px-4 py-2 shadow-md">
        <div className="container mx-auto flex justify-between items-center">
          <a className="text-2xl font-bold text-[#ff5a5f]" href="#">
            bumble
          </a>
          <div className="flex items-center space-x-4 text-sm font-medium">
            <a href="#">The Shop</a>
            <a href="#">The App</a>
            <a href="#">Ambassadors</a>
            <a href="#">Events</a>
            <a href="#">The Buzz</a>
            <a href="#">About</a>
          </div>
        </div>
      </nav>
      <header className="text-center py-12">
        <h1 className="text-4xl font-bold">
          Connect with people you know but haven’t met yet
        </h1>
      </header>
      <section className="container mx-auto grid grid-cols-1 md:grid-cols-3 gap-8 px-4 pb-12">
        {[
          {
            title: "Bumble Date",
            description:
              "On Bumble, women make the first move. We’re leveling the playing field and changing the dynamics of dating. We believe relationships should begin with respect and equality.",
            imageUrl: "/hero.png",
          },
          {
            title: "Bumble Bizz",
            description:
              "Career opportunities come about when you expand your network. On Bumble Bizz, you can pursue a career change, meet team members, or become a mentor.",
            imageUrl: "/hero.png",
          },
          {
            title: "Bumble BFF",
            description:
              "Whether you’re new to a city or looking to expand your social circle, Bumble BFF is a simplified way to create meaningful friendships.",
            imageUrl: "/hero.png",
          },
        ].map((service, index) => (
          <Card
            key={index}
            className="bg-white rounded-lg overflow-hidden shadow-lg"
          >
            <img
              alt={service.title}
              className="w-full"
              height="300"
              src={service.imageUrl}
              style={{
                aspectRatio: "300/300",
                objectFit: "cover",
              }}
              width="300"
            />
            <div className="p-6">
              <h2 className="text-2xl font-bold mb-2">{service.title}</h2>
              <p className="text-gray-700 text-base mb-4">
                {service.description}
              </p>
              <Button className="w-full">Learn More</Button>
            </div>
          </Card>
        ))}
      </section>
    </div>
  );
}
