/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/19UvS96oNrs
 */
import { Button } from "@/components/ui/button"

export function Dating() {
  return (
    <div className="bg-[#fffbe6] px-10 py-20">
      <h1 className="text-4xl font-bold text-center mb-10">Connect with people you know but haven’t met yet</h1>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
        <div className="flex flex-col items-center bg-white p-6 rounded-lg shadow-md">
          <img
            alt="Bumble Date"
            className="rounded-lg mb-4"
            height="300"
            src="/placeholder.svg"
            style={{
              aspectRatio: "200/300",
              objectFit: "cover",
            }}
            width="200"
          />
          <h2 className="text-2xl font-bold mb-3">Bumble Date</h2>
          <p className="text-gray-600 mb-6">
            On Bumble, women make the first move. We’re leveling the playing field and changing the dynamics of dating.
            We believe relationships should begin with respect and equality.
          </p>
          <Button className="bg-[#ffcc00] text-black">Learn More</Button>
        </div>
        <div className="flex flex-col items-center bg-white p-6 rounded-lg shadow-md">
          <img
            alt="Bumble Bizz"
            className="rounded-lg mb-4"
            height="300"
            src="/placeholder.svg"
            style={{
              aspectRatio: "200/300",
              objectFit: "cover",
            }}
            width="200"
          />
          <h2 className="text-2xl font-bold mb-3">Bumble Bizz</h2>
          <p className="text-gray-600 mb-6">
            Career opportunities come about when you expand your network. On Bumble Bizz, you can pursue a career
            change, meet team members, or become a mentor.
          </p>
          <Button className="bg-[#ffcc00] text-black">Learn More</Button>
        </div>
        <div className="flex flex-col items-center bg-white p-6 rounded-lg shadow-md">
          <img
            alt="Bumble BFF"
            className="rounded-lg mb-4"
            height="300"
            src="/placeholder.svg"
            style={{
              aspectRatio: "200/300",
              objectFit: "cover",
            }}
            width="200"
          />
          <h2 className="text-2xl font-bold mb-3">Bumble BFF</h2>
          <p className="text-gray-600 mb-6">
            Whether you’re new to a city or looking to expand your social circle, Bumble BFF is a simplified way to
            create meaningful friendships.
          </p>
          <Button className="bg-[#ffcc00] text-black">Learn More</Button>
        </div>
      </div>
    </div>
  )
}
