/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/iW4XMIF0cE3
 */
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function Features() {
  return (
    <div className="bg-black text-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-4xl font-bold">Our Features you can get</h1>
        <p className="mt-4 text-xl">
          We offer a variety of interesting features that can help increase your productivity at work and manage your
          projects easily
        </p>
        <Button className="mt-6" variant="default">
          Get Started
        </Button>
        <div className="mt-12 grid grid-cols-1 md:grid-cols-3 gap-8">
          <Card className="bg-white text-black">
            <CardContent>
              <img
                alt="Collaboration Teams"
                className="w-full"
                height="200"
                src="/post1.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <h3 className="text-2xl font-bold mt-4">Collaboration Teams</h3>
              <p className="mt-2">Here you can handle projects together with team virtually</p>
            </CardContent>
          </Card>
          <Card className="bg-white text-black">
            <CardContent>
              <img
                alt="Cloud Storage"
                className="w-full"
                height="200"
                src="/post2.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <h3 className="text-2xl font-bold mt-4">Cloud Storage</h3>
              <p className="mt-2">No need to worry about storage because we provide storage up to 2 TB</p>
            </CardContent>
          </Card>
          <Card className="bg-white text-black">
            <CardContent>
              <img
                alt="Daily Analytics"
                className="w-full"
                height="200"
                src="/post3.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <h3 className="text-2xl font-bold mt-4">Daily Analytics</h3>
              <p className="mt-2">We always provide useful information to make it easier for you every day</p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
