/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ylYGii8Ht9e
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { JSX, SVGProps } from "react"

export function Hero1() {
  return (
    <div className="bg-[#2b2e3a] text-white">
      <nav className="container mx-auto flex items-center justify-between py-4">
        <div className="flex items-center space-x-4">
          <div className="bg-[#ff5f5f] p-2 rounded">
            <FlagIcon className="text-white" />
          </div>
          <span className="font-bold">Webflow</span>
        </div>
        <div className="flex items-center space-x-6">
          <Link className="hover:text-gray-300" href="#">
            About
          </Link>
          <Link className="hover:text-gray-300" href="#">
            Services
          </Link>
          <Link className="hover:text-gray-300" href="#">
            Pricing
          </Link>
          <Link className="hover:text-gray-300" href="#">
            Blog
          </Link>
          <Button className="bg-[#ff5f5f] hover:bg-[#e45555]">CONTACT</Button>
        </div>
      </nav>
      <header className="container mx-auto mt-12 flex flex-col items-center text-center">
        <span className="mb-2 text-sm font-semibold uppercase tracking-widest text-[#ff5f5f]">Webflow Expert</span>
        <h1 className="mb-4 text-6xl font-bold leading-none">Making Digital Products</h1>
        <p className="mb-6 max-w-2xl text-lg">
          Agency provides a full service range including technical skills, design, business understanding.
        </p>
        <div className="flex items-center space-x-4">
          <Button className="bg-[#ff5f5f] hover:bg-[#e45555]">EXPLORE WORK</Button>
          <Button variant="ghost">Contact Me</Button>
        </div>
      </header>
      <div className="container mx-auto mt-12 flex justify-between">
        <div className="relative">
          <div className="absolute -left-24 -top-24 w-96 h-96 bg-[#6c63ff] rounded-full" />
          <img
            alt="Laptop"
            className="relative z-10"
            height="400"
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/400",
              objectFit: "cover",
            }}
            width="400"
          />
        </div>
        <div className="flex space-x-8">
          <div className="flex flex-col items-center">
            <div className="mb-4 w-24 h-24 rounded-full bg-[#ff5f5f]" />
            <ImageIcon className="text-[#ff5f5f]" />
          </div>
          <Avatar>
            <AvatarImage alt="Profile picture" src="/placeholder.svg?height=200&width=200" />
            <AvatarFallback>W</AvatarFallback>
          </Avatar>
        </div>
      </div>
    </div>
  )
}


function FlagIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}

function ImageIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  );
}