/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gI2qIKWHJDP
 */
import { Button } from "@/components/ui/button"

export function Hero2() {
  return (
    <div className="bg-[#2b2e3a] text-white min-h-screen">
      <div className="container mx-auto px-4 py-12">
        <div className="flex flex-col lg:flex-row lg:space-x-6">
          <div className="lg:w-1/2">
            <div className="relative mb-6 lg:mb-0">
              <div className="absolute top-0 left-0 z-10 w-40 h-40 bg-[#ff4820] rounded-full flex items-center justify-center text-4xl font-bold text-white">
                webflow
              </div>
              <img
                alt="Webflow screenshot"
                className="relative z-20 mx-auto"
                height="400"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "600/400",
                  height: "auto",
                  maxWidth: "100%",
                  objectFit: "cover",
                }}
                width="600"
              />
            </div>
          </div>
          <div className="lg:w-1/2">
            <div className="mb-6">
              <h2 className="text-3xl font-bold mb-3">ABOUT WEBFLOW</h2>
              <p className="text-2xl font-bold mb-4">Website Without The Dev Time</p>
              <p className="mb-4">Provides a full service range</p>
              <p>
                Ability to put themselves in the merchant's shoes. It is meant to partner on the long run, and work as
                an extension of the merchant's team.
              </p>
            </div>
            <Button className="bg-[#ff4820] hover:bg-[#e0421e] text-white">ABOUT WEBFLOW</Button>
          </div>
        </div>
      </div>
    </div>
  )
}
