/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/io5dAoFUsGR
 */
import { Button } from "@/components/ui/button"

export function Hero3() {
  return (
    <div className="max-w-screen-xl mx-auto px-6">
      <header className="flex justify-between items-center py-6">
        <div className="flex items-center space-x-4">
          <img alt="Blazity logo" className="h-8" src="/placeholder.svg" />
          <nav className="hidden md:flex space-x-6">
            <a className="text-gray-600 hover:text-orange-500" href="#">
              Services
            </a>
            <a className="text-gray-600 hover:text-orange-500" href="#">
              About Us
            </a>
            <a className="text-gray-600 hover:text-orange-500" href="#">
              Our Work
            </a>
            <a className="text-gray-600 hover:text-orange-500" href="#">
              Career
            </a>
            <a className="text-gray-600 hover:text-orange-500" href="#">
              Open Source
            </a>
            <a className="text-gray-600 hover:text-orange-500" href="#">
              Blog
            </a>
          </nav>
        </div>
        <Button className="bg-orange-500 hover:bg-orange-600 text-white">Get a quote</Button>
      </header>
      <main className="mt-16">
        <section className="text-center">
          <h1 className="text-6xl font-bold text-gray-800 mb-4">Next.js and React development experts</h1>
          <p className="text-xl text-gray-600 mb-6">
            We're a team of engineers using headless and composable architecture to create powerful web experiences
          </p>
          <div className="flex justify-center space-x-4">
            <Button className="bg-orange-500 hover:bg-orange-600 text-white">Contact Us</Button>
            <Button variant="outline">Our services</Button>
          </div>
        </section>
        <section className="mt-16">
          <h2 className="text-center text-lg font-semibold text-gray-800 mb-4">CERTIFIED PARTNERS:</h2>
          <div className="flex justify-center space-x-4">
            <img alt="Vercel" className="h-6" src="/placeholder.svg" />
            <img alt="Contentful" className="h-6" src="/placeholder.svg" />
            <img alt="Builder.io" className="h-6" src="/placeholder.svg" />
            <img alt="Hygraph" className="h-6" src="/placeholder.svg" />
            <img alt="Shopify Partners" className="h-6" src="/placeholder.svg" />
          </div>
        </section>
      </main>
    </div>
  )
}
